### ISSUE TITLE
Ornamental Dirt's harvest speed unaffected by shovels

### ISSUE THREAD

**Issue by Not-February** [maideniles/Maiden-s-Marvelous-Materials#10]
No matter what tool I use to try to dig it, shovel or otherwise, it's always the same harvest speed as though I were using no tool at all.

**Comment by maideniles** [comment]
I'll fix this, thank you.

**Comment by Not-February** [comment]
Partially related note: Is it intended to be able to plant crops on ornamental dirt/grass without tilling it first? I love it personally, adds incentive to base in Ornamental Forests, but just wanted to double check.

**Comment by maideniles** [comment]
Well, unfortunately, no, it wasn't intended like that. I forgot to add back in a snippet of code I had in that block right before I changed them and then released the mod.  In the update I'm working on, that will be fixed; tilling ornamental dirt or ornamental grass with a hoe will produce farmland.  There is still some incentive to base there, though, as there is only one way to get the dirt/grass out of the forest. Have you figured it out yet? :)

**Comment by Not-February** [comment]
I haven't! I'll have to poke around more.

(also now I guess I'll have to redo my farms, haha)

**Comment by maideniles** [comment]
Changes have been implemented in the new release. :)
