### ISSUE TITLE
Ornamental Grass can't be silk touch harvested

### ISSUE THREAD

**Issue by Not-February** [maideniles/Maiden-s-Marvelous-Materials#12]
Unsure if intended.

**Comment by maideniles** [comment]
Yes, this is definitely intended.  Remember how I talked about a 'secret' in the description? This is part of it--how do you obtain the special flowery grass? Harvesting with silk touch doesn't do anything, so there must be another way.... ;)

**Comment by maideniles** [comment]
There's a new way to get the ornamental grass in the new update! Enjoy! Closing issue.
