### ISSUE TITLE
Breaking the top half of a door from this mod gives you two doors back

### ISSUE THREAD

**Issue by Not-February** [maideniles/Maiden-s-Marvelous-Materials#14]
Not the hugest deal since they're decorative anyways, I suppose, but still kinda weird.

**Comment by maideniles** [comment]
That is an unusual problem, indeed. I'll look into it and if I can find a fix, I will include it in the update, which should be out soon. :)

**Comment by maideniles** [comment]
I've still not found a solution to this one, so I'll leave this issue open. It's not game-breaking though, so the update is still on track.

**Comment by Not-February** [comment]
That's fair! Gamebreaking issues should come first.

**Comment by gkazan** [comment]
Just fixed it in 96942cf125ba3e687755765398dba9bb35bd59f2
