### ISSUE TITLE
Gem-based tiles cannot be harvested once placed in-world with a pickaxe

### ISSUE THREAD

**Issue by Not-February** [maideniles/Maiden-s-Marvelous-Materials#15]
I noticed this with at least the Rose Quartz Style 6 tiles. Using a pickaxe did not make the block drop, and was about as slow as by hand; it just disappeared when fully broken.

I would theorize that there isn't _any_ tool that currently works with them, but either way I think it would make sense for them to be harvestable with a pickaxe if you make a mistake so you don't have to make more.

**Comment by maideniles** [comment]
They can be picked up with silk touch--I did that on purpose. They are supposed to be like tile would be, somewhat delicate and breakable..so I made the block kind of behave like glass does. They have a hardness of 1, so they aren't too hard to break, but it still takes a little work. And that part I did to prevent people from accidentally breaking them, like you can with glass. Hope this info helps. :)

**Comment by Not-February** [comment]
Oh, okay! I can't remember the wording in the book if it mentioned that, but maybe make it clear that's the intended behavior?

**Comment by maideniles** [comment]
That's a great suggestion; I will implement it in the update I'm working on. :)

**Comment by maideniles** [comment]
explanation about silk touch has been added in the new release. closing this issue. :)
