### ISSUE TITLE
Tinkers Construct update?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [maideniles/Maiden-s-Marvelous-Materials#18]
I noticed my last comment was deleted so I made a new one - any news on a release for Tconstruct support?

**Comment by maideniles** [comment]
I'm sorry if that got deleted; It wasn't on purpose. I was closing out a lot of issues that I had fixed; I probably hit the wrong one, sorry. I had a friend helping me with that but I am not sure where he is at with it as of now. I will get with him and see what the progress is. I'd love to say I can just do it myself right now but my modding skills are pretty novice still; I just managed to put together a pretty mod with what little I know how to do! LOL  I'll get back to you soon. Thanks for being patient. :)

**Comment by P3rf3ctXZer0** [comment]
@maideniles Hey I understand honestly I am not a coder at all. Thanks for being courteous to my curiosity.

**Comment by maideniles** [comment]
My apologies that I've not gotten back to you sooner. I had a death in the family and have not been focusing on mod stuff for the time being. I'll get back to it in a few days. My friend is still working on it, but he's also had a lot on his plate lately as well. We'll do our best to make it happen; just kind of slow getting there. :)

**Comment by P3rf3ctXZer0** [comment]
Anything worth having is worth waiting on.

**Comment by maideniles** [comment]
Hi, just wanted to update you. We are still working on tinkers, slowly but surely. I am on vacation for a couple weeks, won't be around the internet much, but I did want to let you know I haven't forgotten, it's just slow going. My goal is to include the tinkers support when I make the next update. Thanks so much for being so patient.  :)

**Comment by P3rf3ctXZer0** [comment]
Yep and thank you for the update :D

**Comment by maideniles** [comment]
Still working on the tinkers thing. I'm sorry it has been so slow going. It has been a lot more difficult on my part than I anticipated. But we're still poking away at it when we can. Hopefully once I have the next update finished we will have the kinks worked out.

**Comment by SteveBeeblebrox** [comment]
It is on its way :)
![2019-06-09_15 23 38](https://user-images.githubusercontent.com/41750582/59215034-7f9de700-8b75-11e9-91c2-830d2b102417.png)

**Comment by P3rf3ctXZer0** [comment]
Nice : D

**Comment by maideniles** [comment]
Hi, I'm sorry it has been so slow going. I have had some health issues come up over the last few months, and don't have a whole lot of energy or extra time to devote to modding lately. But, I've got some extra help with the mod now, and things are getting done. We're still working on it, of course, but it's coming along much faster now. Thanks for your patience! :)

**Comment by P3rf3ctXZer0** [comment]
Thank you for your effort as well as keeping me up to date.

**Comment by zOnlyKroks** [comment]
Closed due to Mod updating to 1.14.4
