### ISSUE TITLE
Weird forest generation

### ISSUE THREAD

**Issue by tlitookilakin** [maideniles/Maiden-s-Marvelous-Materials#19]
I found a forest biome, but it seems to be bizarrely empty- [Image](https://www.dropbox.com/s/8l6ijybhgzisul4/2019-01-12_21.08.21.png?dl=0)

There's no crashlog, and the only errors I noticed in the client log were sound errors from Dynamic Surroundings, however I did get a copy of the [system details and modlist](https://pastebin.com/8914pFsS) from the beginning of the log.

**Comment by maideniles** [comment]
Oh wow, that's DEFINITELY not how it's supposed to look. I will investigate that and let you know what I come up with. thanks for letting me know.

**Comment by tlitookilakin** [comment]
Thanks for looking into it! ^_^

EDIT: Also, it might not be clear from the image, but I noticed that it seems to generate normally around pools of water and near the edges of the biome. The clusters of trees are all surrounding water pools.

EDIT2: I realized what's happening - for some reason the flower grass doesn't count as grass to the generator, so it's only placing decorations where there's vanilla grass - on the borders of water pools and at the edges of the biome.

**Comment by maideniles** [comment]
Hi, I found the bug and I'm working on a small update that will fix it. Look for it to be available later this evening, or early morning, depending on when Curse approves it. Sorry for the inconvenience!

**Comment by tlitookilakin** [comment]
no problem at all! thanks for your hard work!

**Comment by maideniles** [comment]
The new update is live. Thanks for sticking with me. :)  Closing this issue
