### ISSUE TITLE
Mowzie's Mobs mod conflict

### ISSUE THREAD

**Issue by VallenFrostweaver** [maideniles/Maiden-s-Marvelous-Materials#23]
Maiden's: 3.2
Mowzie's: 1.5.4
Forge: 14.23.5.2808

When you visit the ornamental forest the Lantern mobs will spawn there (typically spawn only in Roofed forest) but in mass quantities and ignores settings in config to reduce or eliminate the mob spawning. Something about the forest is calling a mob spawn in the area. No crash reports but if you put these mods together (I also used Nature's Compass mod to find ornamental forest quickly) this will quickly overrun your world with Lantern entities. I would report this to Mowzie but I suspect in my testing that it is a Maiden's Marvelous Materials issue. If you need more info from me, let me know.

**Comment by gkazan** [comment]
Have you fully confirmed that it is an issue with only Mowzie's mobs, by this I mean are you only playing with Mowzie's mobs and this mod?

**Comment by VallenFrostweaver** [comment]
Yes. I created another simple 3 mod modpack with MMM and Mowzies plus Nature's Compass so I could find the biome. I haven't experienced this with any other biomes mods as of yet and the spawning rules get ignored regardless of Mowzies config changes for the MMM ornamental forest biome only. It is entirely possible that it's a Mowzie issue so if you can't find a cause here I can report there as well.

**Comment by StyxSouls** [comment]
I think it might be Mowzie's Mobs as when I put Realistic Terrain Generator into a pack I was making, any and all roofed forests began mass producing lanterns at an alarming rate.
