### ISSUE TITLE
Gatherer's Glee potion not respecting block metadata when harvesting.

### ISSUE THREAD

**Issue by jaynesb** [maideniles/Maiden-s-Marvelous-Materials#25]
Forge: 14.23.5.2838
Maiden's: 3.3

When mining blocks that differentiate themselves by metadata (ex: vanilla Minecraft's logs, ores from Thermal Expansion,  etc), the Gatherer's Glee potion effect is ignoring metadata when choosing which blocks to drop extras of. 

For instance, when mining birch logs with the Gatherer's Glee potion effect, instead of dropping additional birch logs, the original birch logs are mined (as normal) and additional oak logs are dropped. The additional logs should also be birch.

**Comment by maideniles** [comment]
hi, we are working on a fix for this. thanks for bringing it to our attention. :)

**Comment by zOnlyKroks** [comment]
Closed due to release of 1.14.4
