### ISSUE TITLE
Flower Power duplicates dirt

### ISSUE THREAD

**Issue by Lykrast** [maideniles/Maiden-s-Marvelous-Materials#26]
Version: 3.3

Breaking Ornamental Grass with a Shovel enchanted with Flower Power drops both the Ornamental Grass and Dirt, allowing for duplication.

**Comment by maideniles** [comment]
Ah, that's an old bug I thought I'd already fixed. I'll take a look and the correction will be added to the next update. Thank you! :)

**Comment by zOnlyKroks** [comment]
Closed due to release of 1.14.4
