### ISSUE TITLE
[Suggestion] Make Vanishing Flowers instantly breakable

### ISSUE THREAD

**Issue by Lykrast** [maideniles/Maiden-s-Marvelous-Materials#27]
Vanishing Flowers made with the Fancy Feet enchantment take some time to break, making them break instantly would be a great qol change to make it not deter digging too much.

**Comment by maideniles** [comment]
Thanks for the suggestion, I will add that. :)

**Comment by maideniles** [comment]
I've implemented that change for you. It will be included in the next update that comes out. No eta on that yet; it's a work in progress. I've had to ask for assistance due to some health issues that have come up, but rest assured we are working on it. :)
