### ISSUE TITLE
 [Suggestion] Make real liquids

### ISSUE THREAD

**Issue by lublak** [maideniles/Maiden-s-Marvelous-Materials#28]
It could use for "colorful lakes" also can store in tanks.
Also needed for https://github.com/maideniles/Maiden-s-Marvelous-Materials/issues/18?
I think it might have the same properties as "dyed" water.

![grafik](https://user-images.githubusercontent.com/44057030/62959862-c1f3d680-bdf9-11e9-8153-c64d061d113c.png)

**Comment by zOnlyKroks** [comment]
Closed due to release of 1.14.4
